# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories_size',
            old_name='user',
            new_name='accessories',
        ),
        migrations.AddField(
            model_name='accessories_size',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
