# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-19 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190618_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Piping',
        ),
        migrations.RenameField(
            model_name='piping',
            old_name='Schedule',
            new_name='Piping',
        ),
    ]
