# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-19 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190619_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piping',
            old_name='Piping',
            new_name='piping',
        ),
    ]
