# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-10 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190703_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Accessories')),
            ],
        ),
    ]
