# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-13 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_totalcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalcost',
            old_name='description',
            new_name='droppipe_acess_description',
        ),
        migrations.RenameField(
            model_name='totalcost',
            old_name='total_price',
            new_name='droppipe_acess_total_price',
        ),
        migrations.RenameField(
            model_name='totalcost',
            old_name='unit_price',
            new_name='droppipe_acess_total_quantity',
        ),
        migrations.RemoveField(
            model_name='totalcost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='totalcost',
            name='quantity',
        ),
        migrations.AddField(
            model_name='totalcost',
            name='droppipe_description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='droppipe_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='droppipe_total_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='header_acess_description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='header_acess_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='header_acess_total_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='header_description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='header_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='header_total_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='manifold_acess_description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='manifold_acess_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='manifold_acess_total_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='manifold_description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='manifold_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='totalcost',
            name='manifold_total_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
